// The Library feed — real YouTube videos, embedded and credited, never hosted.
//
// Generated by `npm run ingest:youtube` (scripts/ingest-youtube.mjs) from the
// channel list in data/channels.json. Do not hand-edit src/data/library.json;
// the next ingest overwrites it. See docs/YOUTUBE-INGEST-PLAN.md.
//
// Phase A ships this as a committed snapshot. Phase B moves it behind Postgres +
// an Apify webhook, at which point this module becomes the DB read and everything
// downstream of it stays the same.

import raw from "@/data/library.json";
import type { Discipline } from "./hub";

export interface LibraryCreator {
  name: string;
  handle: string | null;
  url: string | null;
  kind: "athlete" | "creative" | "media";
}

export interface LibraryItem {
  id: string;
  videoId: string;
  title: string;
  url: string;
  discipline: Discipline;
  creator: LibraryCreator;
  /** Who's in it. Null until the Phase-C classifier lands — a blank credit beats a wrong one. */
  athlete: string | null;
  publishedAt: string | null;
  durationSeconds: number | null;
  viewCount: number | null;
  kind: "video" | "short" | "stream";
}

/**
 * A channel we ingest from, as a roster entry rather than a feed source. This is
 * the seed for claimable profiles (product plan §5) — avatar, reach, and the
 * `unclaimed → claimed` state the marketplace profile shares.
 */
export interface CreatorProfile {
  channelId: string;
  name: string;
  handle: string | null;
  url: string;
  description: string | null;
  avatar: string | null;
  subscriberCount: number | null;
  videoCount: number | null;
  kind: "athlete" | "creative" | "media";
  claimState: "unclaimed" | "invited" | "claimed";
}

export const LIBRARY: LibraryItem[] = raw.items as LibraryItem[];

export const CREATORS: CreatorProfile[] = (raw.creators ?? []) as CreatorProfile[];

export const LIBRARY_GENERATED_AT: string | null = raw.generatedAt;

export function formatSubscribers(count: number | null): string | null {
  if (!count) return null;
  if (count >= 1_000_000) return `${(count / 1_000_000).toFixed(1).replace(/\.0$/, "")}M`;
  if (count >= 1_000) return `${Math.round(count / 1_000)}K`;
  return String(count);
}

/** YouTube always serves mqdefault; maxresdefault is missing on plenty of older uploads. */
export function thumbnailFor(videoId: string, res: "max" | "hq" = "max"): string {
  const file = res === "max" ? "maxresdefault" : "hqdefault";
  return `https://i.ytimg.com/vi/${videoId}/${file}.jpg`;
}

export function embedFor(videoId: string): string {
  // nocookie + no related-video spray keeps the Library feeling like ours.
  return `https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1&rel=0&modestbranding=1`;
}

export function formatDuration(seconds: number | null): string | null {
  if (!seconds) return null;
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  return h
    ? `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`
    : `${m}:${String(s).padStart(2, "0")}`;
}

export function formatViews(views: number | null): string | null {
  if (!views) return null;
  if (views >= 1_000_000) return `${(views / 1_000_000).toFixed(1).replace(/\.0$/, "")}M views`;
  if (views >= 1_000) return `${Math.round(views / 1_000)}K views`;
  return `${views} views`;
}

// Absolute, not relative — this renders inside a client component, and a "3w ago"
// computed from Date.now() can differ between the server pass and hydration.
// Matches fmtDate() in lib/episodes.ts.
export function formatDate(iso: string | null): string | null {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
